#!/usr/bin/env python

from sand import Sand
from PIL import Image
import numpy as np
from functools import lru_cache

WIDTH = 500
HEIGHT = 500


@lru_cache(maxsize=1)
def get_colors():
    img = Image.open('src/170.png')
    data = np.array(list(img.convert('RGB').getdata()), 'float') / 255.0
    res = []
    for rgb in data:
        res.append(list(rgb))
    np.random.shuffle(res)
    return res


@lru_cache(maxsize=1)
def get_sand():
    return Sand(WIDTH, HEIGHT)


def run_bench():
    colors = get_colors()
    sand = get_sand()
    color = colors[np.random.choice(len(colors))]
    grains = 170

    for x in range(WIDTH):
        for y in range(HEIGHT):
            alpha = np.random.uniform(0.01, 0.2)
            sand.set_rgba(color + [alpha])
            dots = np.array([[float(x), float(y)]])
            sand.paint_dots(dots)
    sand.write_to_png('output/sample.png')


if __name__ == '__main__':
    import timeit
    print(timeit.repeat(
        "run_bench()",
        number=25,
        repeat=10,
        setup="from __main__ import run_bench"))
